log-level: INFO
activity:
  - PlayerMoveBlockEvent
  - AsyncPlayerChatEvent
  - PlayerInteractEvent
  - PlayerDropItemEvent
  - PlayerToggleSneakEvent
  - PlayerItemHeldEvent
  - PlayerJoinEvent
  - PlayerChangedWorldEvent
  - CraftItemEvent
  - PrepareItemCraftEvent
  - EnchantItemEvent
  - PrepareItemEnchantEvent
  - InventoryClickEvent
  - PlayerBack
idle-notify:
  enabled: true
  idle: 600 # threshold when to notify (seconds)
  cancel-when-away: true
idle-kick:
  enabled: false
  idle: 1200 # threshold when to kick (seconds)
list-tag:
  enabled: true
  tags:
    away:
      enabled: true
      class: Away
      list: '{0}ยง9#Away'
      describe: 'Away for {0}' # 0 = Duration
      priority: 3
    idle:
      enabled: true
      class: Idle
      list: '{0}ยง3#Idle'
      describe: 'Idle for {0}' # 0 = Duration
      priority: 2
      idle: 60 # threshold when to apply idle tag (seconds)
    bed:
      enabled: true
      class: Bed
      list: '{0}ยง5#Bed'
      describe: 'In bed for {0}' # 0 = Duration
      priority: 1
away-back:
  enabled: true
  override-idle: true
  mentions: true
  activity:
    - AsyncPlayerChatEvent
    - PlayerBedEnterEvent
    - PlayerBedLeaveEvent
    - PlayerBack
version: @VERSION@