logLevel: INFO
idleNotify:
    enabled: false
    idle: 600 # threshold when to notify (seconds)
    activity:
        - PlayerMoveBlockEvent
        - AsyncPlayerChatEvent
        - PlayerInteractEvent
        - PlayerDropItemEvent
        - PlayerToggleSneakEvent
        - PlayerItemHeldEvent
        - PlayerJoinEvent
        - PlayerChangedWorldEvent
        - CraftItemEvent
        - PrepareItemCraftEvent
        - EnchantItemEvent
        - PrepareItemEnchantEvent
        - InventoryClickEvent
idleKick:
    enabled: false
    idle: 1200 # threshold when to kick (seconds)
    activity:
        - PlayerMoveBlockEvent
        - AsyncPlayerChatEvent
        - PlayerInteractEvent
        - PlayerDropItemEvent
        - PlayerToggleSneakEvent
        - PlayerItemHeldEvent
        - PlayerJoinEvent
        - PlayerChangedWorldEvent
        - CraftItemEvent
        - PrepareItemCraftEvent
        - EnchantItemEvent
        - PrepareItemEnchantEvent
        - InventoryClickEvent
awayBack:
    enabled: false
    overrideIdle: true
    mentions: true
    activity:
        - AsyncPlayerChatEvent
        - PlayerBedEnterEvent
        - PlayerBedLeaveEvent
listTag:
    enabled: false
    idle: 60 # threshold when to apply idle tag (seconds)
    activity:
        - PlayerMoveBlockEvent
        - AsyncPlayerChatEvent
        - PlayerInteractEvent
        - PlayerDropItemEvent
        - PlayerToggleSneakEvent
        - PlayerItemHeldEvent
        - PlayerJoinEvent
        - PlayerChangedWorldEvent
        - CraftItemEvent
        - PrepareItemCraftEvent
        - EnchantItemEvent
        - PrepareItemEnchantEvent
        - InventoryClickEvent
version: @VERSION@