logLevel: INFO
idleNotify:
    enabled: false
    idle: 600 # threshold when to notify (seconds)
    activity:
        - PlayerMoveEvent
        - AsyncPlayerChatEvent
        - PlayerInteractEvent
        - PlayerDropItemEvent
        - PlayerToggleSneakEvent
        - PlayerItemHeldEvent
        - PlayerJoinEvent
        - PlayerChangedWorldEvent
        - EnchantItemEvent
        - PrepareItemEnchantEvent
        - InventoryClickEvent
idleKick:
    enabled: false
    idle: 1200 # threshold when to kick (seconds)
    activity:
        - PlayerMoveEvent
        - AsyncPlayerChatEvent
        - PlayerInteractEvent
        - PlayerDropItemEvent
        - PlayerToggleSneakEvent
        - PlayerItemHeldEvent
        - PlayerJoinEvent
        - PlayerChangedWorldEvent
        - EnchantItemEvent
        - PrepareItemEnchantEvent
        - InventoryClickEvent
awayBack:
    enabled: false
    overrideIdle: true
    mentions: true
    activity:
        - AsyncPlayerChatEvent
        - PlayerBedEnterEvent
        - PlayerBedLeaveEvent
listTag:
    enabled: false
    idle: 60 # threshold when to apply idle tag (seconds)
    activity:
        - PlayerMoveEvent
        - AsyncPlayerChatEvent
        - PlayerInteractEvent
        - PlayerDropItemEvent
        - PlayerToggleSneakEvent
        - PlayerItemHeldEvent
        - PlayerJoinEvent
        - PlayerChangedWorldEvent
        - EnchantItemEvent
        - PrepareItemEnchantEvent
        - InventoryClickEvent
messages:
    requiresPlayer: '-> §cOnly in-game players§r can use the {1} command' #1 = Command Label
    commandDisabled: '-> Command §cdisabled§r: {1}' # 1 = Command Label
    playerNotFound: '-> Player §enot found§r: {1}' # 1 = <Player>
    reload: '-> {1} plugin §2reloaded' # 1 = Plugin Name
    awayAlready: '-> You have §ealready been away§r {1} for {2}' # 1 = Duration, 2 = Reason
    +awayDefaultReason: 'no reason'
    awayBroadcast: '§8{0,time,HH:mm:ss} {1}§8 is §3away§8 for §7{2}' # 1 = Player Display Name, 2 = Away Reason
    backBroadcast: '§8{0,time,HH:mm:ss} {1}§8 is §6back§8 after §7{2}§8 for §7{3}' # 1 = Player Display Name, 2 = Away Reason, 3 = Away Duration
    backNotAway: '-> You are §enot currently away'
    mentions: '-> {1}§r has been §3away§r {2} for: §7{3}' # 1 = Player Display Name, 2 = Away Duration, 3 = Reason
    mentionsSummary:
        format: '-> Your name was §dmentioned§r by: {1}' # 1 = Players
        +player: '{0} §8({1} ago)§r' # 0 = Display Name, 1 = Duration Since Last Mention
        +delimiter: ', '
    who:
        list:
            format: '-> §2Who§r: {2,choice,0#§7No one online|1#{1} §8({2})}' # 1 = Players, 2 = Count
            +player: '{0}§r' # 0 = Display Name
            +tagAway: '{0}§3#Away§r' # 0 = Formatted player
            +tagIdle: '{0}§3#Idle§r' # 0 = Formatted player
            +delimiter: '§7,§r '
        connected: '-> {1}§r connected {2} ago' # 1 = Display Name, 2 = Last Connected Duration
        connectedAway: '-> {1}§r connected {2} ago and has been §3away§r {3} for: §7{4}' # 1 = Display Name, 2 = Last Connected Duration, 3 = Away Duration, 4 = Reason
        connectedIdle: '-> {1}§r connected {2} ago and has been §3idle§r {3}' # 1 = Display Name, 2 = Last Connected Duration, 3 = Idle Duration
        disconnected: '-> {1}§r §9disconnected§r {2} ago' # 1 = Player Name, 2 = Last Disconnected Duration
        +unknownConnected: '§osome time§r'
    idleNotify: null # 1 = Current Idle Duration, 2 = Kick Idle Duration
    idleBroadcast: '§8{0,time,HH:mm:ss} {3}§8 has been §3idle§8 for {1}' # 1 = Current Idle Duration, 2 = Kick Idle Duration, 3 = Player Display Name
    idleBackBroadcast: '§8{0,time,HH:mm:ss} {3}§8 is §6back§8 after being idle for {1}' # 1 = Current Idle Duration, 2 = Kick Idle Duration, 3 = Player Display Name
    +idleKickReason: 'Idle for {0}' # 0 = Kick Idle Duration
    listTag:
        +away: '§3#Away'
        +idle: '§3#Idle'
        +bed: '§5#Bed'
version: @VERSION@