name: @NAME@
description: Track player based events
softdepend: [MessageManager]
version: @VERSION@
author: @AUTHOR@
main: @MAIN@
commands:
    'playeractivity:away':
        aliases: [away, afk]
        description: Configure your status as not active
        permission: playeractivity.away
        usage: /<command>[ <Reason>]
    'playeractivity:back':
        aliases: back
        description: Configure your status as no longer away
        permission: playeractivity.back
        usage: /<command>
    'playeractivity:who':
        aliases: who
        description: View status of players
        permission: playeractivity.who
        usage: /<command>[ <Player>]
    'playeractivity:reload':
        description: Reload PlayerActivity plugin
        permission: playeractivity.reload
permissions:
    playeractivity.hide:
        description: Player will be hidden from all automatic status/notifications
        default: false
        children:
            playeractivity.who.hide: true
            playeractivity.idle.ignore: true
    playeractivity.who.hide:
        description: Player will be hidden from who command
        default: false
    playeractivity.idle.ignore:
        description: Player will not be notified or kicked if they go idle
        default: false
        children:
            playeractivity.idle.ignore.notify: true
            playeractivity.idle.ignore.kick: true
            playeractivity.idle.ignore.listtag: true
    playeractivity.idle.ignore.notify:
        description: IdleNotify will not notify if player goes idle
        default: false
    playeractivity.idle.ignore.kick:
        description: IdleKick will not kick player if player goes idle
        default: false
    playeractivity.idle.ignore.listtag:
        description: ListTag will not tag player if player goes idle
        default: false
    playeractivity.away:
        description: Can use away command
        default: false
    playeractivity.back:
        description: Can use back command
        default: false
    playeractivity.who:
        description: Can use who command
        default: false
    playeractivity.awayback:
        description: Can use away, back, and who commands
        default: true
        children:
            playeractivity.away: true
            playeractivity.back: true
            playeractivity.who: true
    playeractivity.reload:
        description: Can use reload command
        default: op