name: @NAME@
description: Track player based events
softdepend: [MessageManager]
version: @VERSION@
author: @AUTHOR@
main: edgruberman.bukkit.playeractivity.Main
commands:
    away:
        description: Configures your status as not active
        permission: playeractivity.away
        usage: /<command>[ <Reason>] - Set yourself as away
    back:
        description: Configures your status as active
        permission: playeractivity.back
        usage: /<command> - Set yourself as back
    who:
        description: View status of players
        permission: playeractivity.who
        usage: |
            /<command> - Show current players
            /<command> <Player> - Show player activity
permissions:
    playeractivity.idlekick.ignore:
        description: IdleKick will not warn or kick
        default: false
    playeractivity.away:
        description: Can use away command
        default: false
    playeractivity.back:
        description: Can use back command
        default: false
    playeractivity.who:
        description: Can use who command
        default: false
        children:
            playeractivity.who.list: true
            playeractivity.who.detail: true
    playeractivity.who.list:
        description: Can use list action of who command
        default: false
    playeractivity.who.detail:
        description: Can use detail action of who command
        default: false
    playeractivity.awayback:
        description: Can use away, back, and who commands
        default: op
        children:
            playeractivity.away: true
            playeractivity.back: true
            playeractivity.who: true