idleNotify:
    enabled: false
    activity:
        - PlayerMoveEvent
        - PlayerChatEvent
        - PlayerInteractEvent
        - PlayerDropItemEvent
        - PlayerToggleSneakEvent
        - PlayerItemHeldEvent
        - PlayerJoinEvent
        - PlayerChangedWorldEvent
        - EnchantItemEvent
        - PrepareItemEnchantEvent
        - InventoryClickEvent
        - AwayBack.PlayerBackCommand
    idle: 600 # threshold when to notify (seconds)
    private: null # 1 = Current Idle Duration, 2 = Kick Idle Duration
    broadcast: '%3$s&_ has been &6idle&_ for %1$s' # 1 = Current Idle Duration, 2 = Kick Idle Duration, 3 = Player Display Name
    backBroadcast: '%3$s&_ is &eback&_ after being idle for %1$s' # 1 = Current Idle Duration, 2 = Kick Idle Duration, 3 = Player Display Name
idleKick:
    enabled: false
    activity:
        - PlayerMoveEvent
        - PlayerChatEvent
        - PlayerInteractEvent
        - PlayerDropItemEvent
        - PlayerToggleSneakEvent
        - PlayerItemHeldEvent
        - PlayerJoinEvent
        - PlayerChangedWorldEvent
        - EnchantItemEvent
        - PrepareItemEnchantEvent
        - InventoryClickEvent
        - AwayBack.PlayerBackCommand
    idle: 600 # threshold when to kick (seconds)
    reason: 'Idle for %1$s' # 1 = Kick Idle Duration
awayBack:
    enabled: false
    commands:
        away: away
        back: back
    overrideIdle: true
    activity:
        - PlayerChatEvent
        - PlayerBedEnterEvent
        - PlayerBedLeaveEvent
    reason: 'no reason'
    away: '%1$s&_ is &6away&_ for &7%2$s' # 1 = Player Display Name, 2 = Away Reason
    back: '%1$s&_ is &eback&_ after %3$s for &7%2$s' # 1 = Player Display Name, 2 = Away Reason, 3 = Away Duration
    mentions: '&f%1$s&_ has been &6away&_ %2$s for: &7%3$s' # 1 = Player Display Name, 2 = Away Duration, 3 = Reason
who:
    enabled: false
    commands:
        who: who
    list:
        format: 'Who: %1$s' # 1 = Player List
        delimiter: ', '
        name: '&f%s&_' # 1 = Player Display Name
        away: '%1$s&6#Away&_' # 1 = Formatted name
        idle: '%1$s&6#Idle&_' # 1 = Formatted name
    detail:
        connected: '&f%1$s&_ connected %2$s ago' # 1 = Player Display Name, 2 = Last Connected Duration
        away: '%1$s and has been &6away&_ %2$s for: &7%3$s' # 1 = Formatted connected, 2 = Away Duration, 3 = Reason
        idle: '%1$s and has been &6idle&_ %2$s' # 1 = Formatted connected, 2 = Idle Duration
        disconnected: '%1$s&_ disconnected %2$s ago' # 1 = Player Name, 2 = Last Connected Duration
listTag:
    enabled: false
    idle: 60
    activity:
        - PlayerMoveEvent
        - PlayerChatEvent
        - PlayerInteractEvent
        - PlayerDropItemEvent
        - PlayerToggleSneakEvent
        - PlayerItemHeldEvent
        - PlayerJoinEvent
        - PlayerChangedWorldEvent
        - EnchantItemEvent
        - PrepareItemEnchantEvent
        - InventoryClickEvent
        - AwayBack.PlayerBackCommand
    awayTag: '&6#Away'
    idleTag: '&6#Idle'
    bedTag: '&8#Bed' 
logLevel: INFO
version: @VERSION@