IdleKick:
    enabled: false
    activity:
        - PlayerMoveEvent
        - PlayerChatEvent
        - PlayerInteractEvent
        - PlayerDropItemEvent
        - PlayerToggleSneakEvent
        - PlayerItemHeldEvent
        - PlayerJoinEvent
        - EnchantItemEvent
        - PrepareItemEnchantEvent
        - InventoryClickEvent
    warn:
        idle: 300 # seconds at which to warn player of kick; -1 to disable
        private: 'You will be kicked after %2$s of being idle' # 1 = Current Idle Duration, 2 = Kick Idle Duration
        broadcast: '%3$s&_ has been &6idle&_ for %1$s' # 1 = Current Idle Duration, 2 = Kick Idle Duration, 3 = Player Display Name
        backBroadcast: '%3$s&_ is &eback&_ after being idle for %1$s' # 1 = Current Idle Duration, 2 = Kick Idle Duration, 3 = Player Display Name
    kick:
        idle: 600 # seconds of idle to kick; -1 to disable
        reason: 'Idle for %1$s' # 1 = Kick Idle Duration
logLevel: INFO
version: @VERSION.TARGET@