idleKick:
    enabled: false
    activity:
        - PlayerMoveEvent
        - PlayerChatEvent
        - PlayerInteractEvent
        - PlayerDropItemEvent
        - PlayerToggleSneakEvent
        - PlayerItemHeldEvent
        - PlayerJoinEvent
        - EnchantItemEvent
        - PrepareItemEnchantEvent
        - InventoryClickEvent
        - AwayBack.PlayerBackCommand
    warn:
        idle: 300 # seconds at which to warn player of kick; -1 to disable
        private: 'You will be kicked after %2$s of being idle' # 1 = Current Idle Duration, 2 = Kick Idle Duration
        broadcast: '%3$s&_ has been &6idle&_ for %1$s' # 1 = Current Idle Duration, 2 = Kick Idle Duration, 3 = Player Display Name
        backBroadcast: '%3$s&_ is &eback&_ after being idle for %1$s' # 1 = Current Idle Duration, 2 = Kick Idle Duration, 3 = Player Display Name
        awayBroadcastOverride: true
    kick:
        idle: 600 # seconds of idle to kick; -1 to disable
        reason: 'Idle for %1$s' # 1 = Kick Idle Duration
awayBack:
    enabled: false
    activity:
        - PlayerChatEvent
        - PlayerBedEnterEvent
        - PlayerBedLeaveEvent
    reason: 'no reason'
    away: '%1$s&_ is &6away&_ for &7%2$s&_' # 1 = Player Display Name, 2 = Away Reason
    back: '%1$s&_ is &eback&_ after %3$s for &7%2$s&_' # 1 = Player Display Name, 2 = Away Reason, 3 = Away Duration
who:
    list:
        format: 'Who: %1$s' # 1 = Player List
        delimiter: ', '
        name: '&f%s&_'
        away: '%1$s&6#Away&_' # 1 = Formatted name
        idle: '%1$s&6#Idle&_' # 1 = Formatted name
    detail:
        connected: '&f%1$s&_ connected %2$s ago' # 1 = Player Display Name, 2 = Last Connected Duration
        away: '%1$s and has been &6away&_ %2$s for: &7%3$s&_' # 1 = Formatted connected, 2 = Away Duration, 3 = Reason
        idle: '%1$s and has been &6idle&_ %1$s' # 1 = Formatted connected, 2 = Idle Duration
        disconnected: '%1$s&_ disconnected %2$s ago' # 1 = Player Name, 2 = Last Connected Duration 
logLevel: INFO
version: @VERSION@